#端口号
server:
  port: 8080
#数据库配置
spring:
  datasource:
    username: root
    password: 20010720Lmx
    url: jdbc:mysql://47.109.206.82/news_management?&useSSL=false&serverTimezone=UTC&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  transaction:
    rollback-on-commit-failure: true
    default-timeout: 30